name: cui parent pom
description: Parent pom for all CUI-OSS projects

release:
  current-version: 1.4.3
  next-version: 1.4-SNAPSHOT
  create-github-release: true

maven-build:
  java-versions: '["21"]'
  java-version: '21'
  enable-snapshot-deploy: true
  maven-profiles-release: 'release-pom'
  npm-cache: false

sonar:
  project-key: cuioss_cuioss-parent-pom
  enabled: false
  skip-on-dependabot: true

pages:
  reference: cui-parent-pom
  deploy-at-release: true

github-automation:
  auto-merge-build-versions: true
  auto-merge-build-timeout: 300
