name: cui parent pom
description: Parent pom for all CUI-OSS projects

release:
  current-version: 1.4.4
  next-version: 1.4-SNAPSHOT
  create-github-release: true

maven-build:
  java-versions: '["21"]'
  java-version: '21'
  enable-snapshot-deploy: true
  maven-profiles-release: 'release-pom'
  npm-cache: false

sonar:
  project-key: cuioss_cuioss-parent-pom
  enabled: false
  skip-on-dependabot: true

pages:
  reference: cui-parent-pom
  deploy-at-release: true

github-automation:
  auto-merge-build-versions: true
  auto-merge-build-timeout: 300

consumers:
  - cui-core-ui-model
  - cui-http
  - cui-java-module-template
  - cui-java-tools
  - cui-jsf-test-basic
  - cui-test-generator
  - cui-test-juli-logger
  - cui-test-keycloak-integration
  - cui-test-mockwebserver-junit5
  - cui-test-value-objects
  - OAuthSheriff
  - cui-portal-core
  - cui-portal-ui
  - cui-jsf-components
  - cui-open-rewrite

dependency-propagation:
  group-id: de.cuioss
  artifact-id: cui-java-parent
  scope: parent
