= cui-parent-pom
:toc: macro
:toclevels: 3
:sectnumlevels: 1

[.discrete]
== Status

image:https://github.com/cuioss/cuioss-parent-pom/actions/workflows/maven.yml/badge.svg[Java CI with Maven,link=https://github.com/cuioss/cuioss-parent-pom/actions/workflows/maven.yml]
image:http://img.shields.io/:license-apache-blue.svg[License,link=http://www.apache.org/licenses/LICENSE-2.0.html]
image:https://img.shields.io/maven-central/v/de.cuioss/cui-parent-pom.svg?label=Maven%20Central["Maven Central", link="https://central.sonatype.com/artifact/de.cuioss/cui-parent-pom"]

== What is it?

Parent pom for cui-open-source-projects. It defines and configures a number of maven-plugins, unifying the descendant modules.
It aims at modules being at least Java 21. It defines the sonatype-repositories as read and deploy repositories.

Maven-site result can be found https://cuioss.github.io/cui-parent-pom/[Project-Home-Page]

toc::[]

== Modules

* link:cui-java-bom/README.adoc[cui-java-bom] - Java dependency management
* link:java-ee-bom/README.adoc[java-ee-bom] - Jakarta EE dependency management

== Documentation

* link:doc/Build.adoc[Build Information] - Building the project, reproducible builds, PlantUML
* link:doc/open-rewrite-recipes.adoc[OpenRewrite Recipes] - Code modernization and formatting recipes (pre-commit profile)
* link:doc/signing_key.adoc[Signing Keys] - Creating the GPG signing key for Maven Central

== Usage

=== As a parent POM

[source,xml]
----
<parent>
   <groupId>de.cuioss</groupId>
   <artifactId>cui-parent-pom</artifactId>
   <version>1.6.2</version> <!-- use the latest release -->
</parent>
----

=== Including dependency management

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>de.cuioss</groupId>
            <artifactId>java-ee-10-bom</artifactId>
            <!-- version.cui.parent is set implicitly by cui-parent-pom; override only if needed -->
            <version>${version.cui.parent}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

== Usage for Quarkus modules

Quarkus projects inherit `cui-quarkus-parent` instead of `cui-java-parent`. It supplies
`version.quarkus` as an *inherited* property, so `quarkus-maven-plugin` (a build extension,
resolved before dependency management applies) and the Quarkus artifacts are driven by one
value and cannot drift apart.

[source,xml]
----
<parent>
    <groupId>de.cuioss</groupId>
    <artifactId>cui-quarkus-parent</artifactId>
    <version>1.6.2</version> <!-- use the latest release -->
</parent>

<build>
    <plugins>
        <!-- no <version>, no <executions>: both come from the inherited pluginManagement -->
        <plugin>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-maven-plugin</artifactId>
        </plugin>
    </plugins>
</build>
----

See link:cui-java-bom/cui-java-parent/cui-quarkus-parent/README.adoc[cui-quarkus-parent] for
projects that carry competing BOM imports, and for the supported emergency-pin override.

== Usage for Standard java-modules

[source,xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.cuioss</groupId>
        <artifactId>cui-java-parent</artifactId>
        <version>1.6.2</version>
    </parent>
    <artifactId>cui-java-sample</artifactId>
    <name>cui java sample</name>
    <packaging>pom</packaging>
    <description>Sample usage of parent-pom</description>
    <dependencies>
        <!-- Provided-->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <!-- Unit testing -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>
</project>
----
